application: iketrial
version: 1
runtime: python
api_version: 1

handlers:
# trial.
 - url: /trial/cron/.*
   script: trial/views.py
   login: admin

 - url: /trial/.*
   script: trial/views.py

# Static files.
 - url: /media
   static_dir: media

# fbweb
 - url: /fbweb/.*
   script: fbweb/views.py

# fbnews
 - url: /fbnews/develop/.*
   script: fbnews/views.py
   login: admin

 - url: /fbnews/aggregate/
   script: fbnews/views.py
   login: admin

 - url: /fbnews/.*
   script: fbnews/views.py

# openid
 - url: /_ah/login_required
   script: do_openid_login.py

 - url: /openid/.*
   script: openid/views.py
   #login: required
